version: '3.8'

services:
  tradehub:
    build:
      context: ../core-service
      dockerfile: Dockerfile
    container_name: core-service
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tradehub.rule=Host(`tradehub.localhost`)"
      - "traefik.http.services.tradehub.loadbalancer.server.port=80"
    restart: unless-stopped

networks:
  app-network:
    driver: bridge